name: Deploying Dev

on:
  workflow_dispatch:
  push:
    branches: [develop]
    
jobs:
  deploy:
    environment: development
    env:
      ECR_REPOSITORY: ${{ vars.DOCKER_IMAGE_NAME }}:latest
      ECS_SERVICE: NextCartService
      ECS_CLUSTER: NextCartCluster
      ECS_TASK_DEFINITION: ./storage/nextcart-task.json
      CONTAINER_NAME: nextcart-api       
      DATABASE_URL: mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:3306/${{ secrets.DB_NAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
      - run: npx prisma migrate deploy
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update task defination file
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_FILE }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ vars.DOCKER_IMAGE_NAME }}:develop
      - name: Deploy ECS tasks
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
